
general:
  listen_address: "127.0.0.1"
  listen_port: 8081
  log_level: "debug"
llm_apis:
  - provider: "openai"
    model: "gpt-4"
    base_url: "http://127.0.0.1:54460"
    rate_limit: 60
    token_limit: 1000
    context_length: 2048
    api_key_name: "OPENAI_API_KEY"
    price: 0.03
    quality: 5
